### ISSUE TITLE
command not found, HTTP/1.1 400 Bad Request

### ISSUE THREAD

**Issue by lee-costa** [jorgedlcruz/cloudflare-grafana#4]
This is my configuration:

        # Endpoint URL for InfluxDB
        InfluxDBURL="localhost" #Your InfluxDB Server, http://FQDN or https://FQDN if using SSL
        InfluxDBPort="8086" #Default Port
        InfluxDB="cloudflare" #Default Database
        InfluxDBUser="" #User for Database
        InfluxDBPassword="" #Password for Database

        # Endpoint URL for login action
        cloudflareapikey="CUSTOM_CREATED_KEY"
        cloudflarezone="ZONE_ID"

I am don't have users or passwords in my database so I assume the above is correct? I also made sure to follow your guide on your website to create the api key. 

Thank you.

**Comment by jorgedlcruz** [comment]
Hello, give it another try with the new script. Best regards
